spring.cloud.stream:
  function:
    definition: domainProcessor 
  kafka:
    bindings:
      domainProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.StringDeserializer
        startOffset: latest
      domainProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.StringSerializer
    binder:
      brokers: localhost:9092
      applicationId: myDomainProcessorApp